apiVersion: v1
kind: Pod
metadata:
  name: test-pod2
spec:
  containers:
  - image: grafana/grafana
    name: grafana
    ports:
      - containerPort: 3000
  - image: prom/prometheus
    name: prometheus
    ports:
      - containerPort: 9090
  - image: prom/node-exporter
    name: node-exporter
    ports:
      - containerPort: 9100